In [1]:
#Import libraries
import pandas as pd 
import geopandas as gpd
from geopandas.tools import geocode
import shapely
from shapely.geometry import Point
import numpy as np
import scipy.stats as stats
import scipy
import seaborn as sns
import matplotlib 
from matplotlib import pyplot as plt
matplotlib.rcParams.update({'font.size': 20})

In [12]:
df_sidewalks = gpd.read_file('Sidewalks.geojson')

In [13]:
df_sidewalks.head()

,OBJECTID,COMPKEY,COMPTYPE,SEGKEY,UNITID,UNITTYPE,UNITDESC,ADDBY,ADDDTTM,ASBLT,...,NATURE_OF_MAINT_RESP,MAINT_FINANCIAL_RESP,MAINTBYRDWYSTRUCT,SWINCOMPLETE,MULTIPLESURFACE,SW_CATEGORY,VARIABLEWIDTHYN,MAINTENANCE_GROUP,SHAPE_Length,geometry
0,1,326162,97,6602,SDW-29552,SDW,42ND AVE SW BETWEEN SW DAWSON ST AND SW BRANDO...,SW DATA LOAD,2007-09-26T17:17:34+00:00,None,...,None,,N,N,N,BLOCK,N,SSRP_SSW1_SWShim,633.140614,"LINESTRING (-122.38556 47.55565, -122.38561 47..."
1,2,304539,97,2970,SDW-10605,SDW,"20TH AVE NE BETWEEN NE 63RD ST AND NE 65TH ST,...",SW DATA LOAD,2007-09-26T17:17:34+00:00,None,...,None,,N,N,N,BLOCK,N,SSRP_NE1_SWShim,333.317559,"LINESTRING (-122.30644 47.67483, -122.30644 47..."
2,3,307902,97,16037,SDW-13339,SDW,N 92ND ST BETWEEN MERIDIAN AVE N AND MERIDIAN ...,SW DATA LOAD,2007-09-26T17:17:34+00:00,None,...,None,,N,N,N,BLOCK,N,SSRP_NW5_SWShim,289.661452,"LINESTRING (-122.33375 47.69603, -122.33257 47..."
3,4,322153,97,9098,SDW-23655,SDW,BEACH DR SW BETWEEN SW GENESEE ST AND SW OREGO...,SW DATA LOAD,2007-09-26T17:17:34+00:00,None,...,None,,N,N,N,BLOCK,N,SSRP_SSW4_SWShim,691.200791,"LINESTRING (-122.40696 47.56491, -122.40624 47..."
4,5,322244,97,20549,SDW-22412,SDW,S JUNEAU ST BETWEEN RAINIER AVE S AND 46TH AVE...,SW DATA LOAD,2007-09-26T17:17:34+00:00,None,...,None,,N,N,N,BLOCK,N,SSRP_SSW2_SWShim,405.561715,"LINESTRING (-122.27708 47.54976, -122.27544 47..."

In [14]:
sidewalk_col = ['INSTALL_DATE','SHAPE_Length','geometry']
sidewalks = df_sidewalks.loc[:,sidewalk_col]
sidewalks.head()

,INSTALL_DATE,SHAPE_Length,geometry
0,1970-01-01T00:00:00+00:00,633.140614,"LINESTRING (-122.38556 47.55565, -122.38561 47..."
1,1970-01-01T00:00:00+00:00,333.317559,"LINESTRING (-122.30644 47.67483, -122.30644 47..."
2,1970-01-01T00:00:00+00:00,289.661452,"LINESTRING (-122.33375 47.69603, -122.33257 47..."
3,1970-01-01T00:00:00+00:00,691.200791,"LINESTRING (-122.40696 47.56491, -122.40624 47..."
4,1970-01-01T00:00:00+00:00,405.561715,"LINESTRING (-122.27708 47.54976, -122.27544 47..."